# Server
spring.application.name=ecommerce-multivendor
server.port=5454

# Database (MariaDB)
spring.datasource.url=jdbc:mariadb://localhost:3306/yt_ecommerce
 spring.datasource.username=${MARIA_DB_USERNAME}
 spring.datasource.password=${MARIA_DB_PASSWORD}


# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Payment keys
razorpay.api.key=${RAZORPAY_API_KEY}                                                                                                                                                                         
razorpay.api.secret=${RAZORPAY_API_SECRET}                                                                                                                                                                   
stripe.secret.key=${STRIPE_SECRET_KEY}                                                                                                                                                                       

