package com.penguinshop.utils;

import java.security.SecureRandom;
import java.util.Random;

import com.penguinshop.model.VerificationCode;
import com.penguinshop.repository.VerificationCodeRepository;

/**
 * <p>This class generates a 6 digit One Time Password
 * with random numbers generated by {@code SecureRandom}</p>
 */
public class OtpUtil{
    public static String generateOtp() {
        int otpLength = 6;

        Random Random = new SecureRandom();

        StringBuilder otp = new StringBuilder(otpLength);
        
        for (int i = 0; i < otpLength; i++) {
            otp.append(Random.nextInt(10));
        }

        System.out.println("GENERATED OTP: " + otp.toString());
        System.out.println(otp);
        return otp.toString();
    }
}
